#!/bin/bash

set -e

: "${1:?❌ Required positional arg NPM_VERSION_TYPE not set - exiting.}"

npm version --git-tag-version false "$1"

NEW_VERSION=$(npm pkg get version)
echo "export const version = $NEW_VERSION;" > ./src/version.ts

echo ""
echo "✅ Version successfully updated to $1 - rememeber to commit!"
