#!/bin/bash

set -e

CMD="$*"

if [ -z "$CMD" ]; then
 echo "You must provide a command, for example: ./scripts/ci npm run test:ci"
fi

echo "Building a development Docker image"
docker build -t switch-and-signal-sessions .

echo "Running ${CMD} in switch-and-signal-sessions container"
docker run --rm \
    -v /app/node_modules \
    -v "$(pwd)":/app \
    -e NPM_TOKEN="$NPM_TOKEN" \
    switch-and-signal-sessions \
    $CMD
