#!/bin/bash

set -e

echo "Building a development Docker image"
docker build -t switch-and-signal-sessions-local-dev .

[[ $# -eq 0 ]] && cmd="bash" || cmd="$@"
echo "Running ${cmd} in the development container"
docker run --rm -it \
    -v /app/node_modules \
    -v "$(pwd)":/app \
    switch-and-signal-sessions-local-dev \
    $cmd
